# Architecture Overview

Software architecture of **{{PROJECT_NAME}}** using the [C4 model](https://c4model.com/).

**Audience:** All team members, from stakeholders to developers.

## C4 Levels

| Level | Diagram | Audience | Question Answered |
|:-----:|---------|----------|-------------------|
| 1 | [System Context](c4-context.md) | Everyone | What does the system do and who uses it? |
| 2 | [Container](c4-container.md) | Technical staff | What are the major building blocks? |
| 3 | [Component](c4-component.md) | Developers | How is each container structured internally? |

## Supplementary Diagrams

| Diagram | When Generated | Purpose |
|---------|----------------|---------|
| [Dynamic](c4-dynamic.md) | Critical flows detected | Show runtime interaction sequences |
| [Deployment](c4-deployment.md) | Infrastructure signals found | Show production topology |

<!-- GENERATION RULES:
  Decision framework (applied by /docs Phase 3):

  ALWAYS generate:
    - README.md (this hub page)
    - c4-context.md (Level 1)
    - c4-container.md (Level 2)

  CONDITIONALLY generate:
    - c4-component.md → if any container has >5 internal modules
    - c4-dynamic.md → if critical flows detected (auth, data pipeline, primary user journey)
    - c4-deployment.md → if deployment signals found (docker-compose, K8s, Terraform, LB config)

  If conditional diagram is NOT generated, its row should be removed
  from the Supplementary Diagrams table above.
-->

## How to Read

1. **Start at Level 1** (Context) — understand scope and boundaries
2. **Zoom into Level 2** (Container) — see technology choices
3. **Dive into Level 3** (Component) — only for containers you work on
4. **Check Dynamic diagrams** — to understand critical runtime flows

## Cross-References

- [Transport](../transport.md) — protocols and exchange formats used between containers
<!-- IF API_COUNT >= 1 -->
<!-- - [API Overview](../api/overview.md) — exposed endpoints and their transports -->
<!-- END IF -->

---

*Generated by `/docs`. Last updated: {{GENERATED_DATE}}*
