#!/bin/bash
# ============================================================================
# commit-validate.sh - Block commits with AI/Claude references
# PreToolUse hook for Bash(git commit:*)
# Exit 0 = allowed, Exit 2 = blocked
# ============================================================================

set -uo pipefail

# === Read hook input (JSON from stdin) - fail gracefully ===
set +o pipefail
INPUT="$(cat 2>/dev/null)"
set -o pipefail
INPUT="${INPUT:-{}}"

# Fail gracefully if no input or invalid JSON
if [[ -z "$INPUT" ]] || [[ "$INPUT" == "{}" ]]; then
    exit 0
fi

# Verify jq is available
if ! command -v jq &>/dev/null; then
    exit 0
fi

# Forbidden patterns (case insensitive)
FORBIDDEN_PATTERNS=(
    # Co-author patterns
    "co-authored-by.*claude"
    "co-authored-by.*anthropic"
    "co-authored-by.*openai"
    "co-authored-by.*gpt"
    "co-authored-by.*ai"
    "co-authored-by.*copilot"
    "co-authored-by.*gemini"
    "co-authored-by.*llm"
    # Generated by patterns
    "generated.*with.*claude"
    "generated.*by.*claude"
    "generated.*with.*ai"
    "generated.*by.*ai"
    "generated.*with.*gpt"
    "generated.*by.*gpt"
    "ai.assisted"
    "ai-assisted"
    # Direct mentions
    "🤖"
    "claude code"
    "claude-code"
    "anthropic"
    "openai"
    "chatgpt"
    "copilot"
)

# Extract tool_name and command (fail gracefully)
TOOL=$(printf '%s' "$INPUT" | jq -r '.tool_name // "unknown"' 2>/dev/null) || TOOL="unknown"
COMMAND=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // ""' 2>/dev/null) || COMMAND=""

# Check if this is a git commit
if [[ "$TOOL" != "Bash" ]]; then
    exit 0
fi

if [[ ! "$COMMAND" =~ ^git[[:space:]]+commit ]]; then
    exit 0
fi

# Extract the commit message
# Patterns: -m "msg", -m 'msg', --message="msg", heredoc
COMMIT_MSG=""

# Pattern 1: -m "message" or -m 'message'
if [[ "$COMMAND" =~ -m[[:space:]]+[\"\']([^\"\']+)[\"\'] ]]; then
    COMMIT_MSG="${BASH_REMATCH[1]}"
fi

# Pattern 2: -m "$(cat <<..." (heredoc)
if [[ "$COMMAND" =~ cat[[:space:]]+\<\<[\'\"]?EOF ]]; then
    # Extract everything between <<EOF and EOF
    COMMIT_MSG=$(echo "$COMMAND" | sed -n '/<<.*EOF/,/EOF/p' | grep -v "EOF" | grep -v "cat <<")
fi

# Pattern 3: --message="..."
if [[ "$COMMAND" =~ --message=[\"\']([^\"\']+)[\"\'] ]]; then
    COMMIT_MSG="${BASH_REMATCH[1]}"
fi

# If no message found, let it pass (will be validated otherwise)
if [[ -z "$COMMIT_MSG" ]]; then
    exit 0
fi

# Check each forbidden pattern
COMMIT_MSG_LOWER=$(echo "$COMMIT_MSG" | tr '[:upper:]' '[:lower:]')

for pattern in "${FORBIDDEN_PATTERNS[@]}"; do
    if echo "$COMMIT_MSG_LOWER" | grep -qiE "$pattern"; then
        echo "═══════════════════════════════════════════════"
        echo "  ❌ COMMIT BLOCKED - AI reference detected"
        echo "═══════════════════════════════════════════════"
        echo ""
        echo "  Forbidden pattern found: $pattern"
        echo ""
        echo "  Commit message:"
        echo "$COMMIT_MSG" | head -5 | sed 's/^/    /'
        echo ""
        echo "  RULE: Commits must NEVER contain:"
        echo "    - Co-Authored-By with Claude/Anthropic/OpenAI/AI"
        echo "    - Generated by/with AI/Claude/GPT"
        echo "    - Direct AI mentions (🤖, claude-code, etc.)"
        echo ""
        echo "═══════════════════════════════════════════════"
        exit 2
    fi
done

# Valid message
echo "✓ Commit validated (no AI reference)"
exit 0
