#!/bin/bash
# ============================================================================
# post-compact.sh - Restore critical context after context compaction
# SessionStart hook for "compact" matcher
# Exit 0 = success, outputs additionalContext to inject into Claude's context
# ============================================================================

set -euo pipefail

# Read hook input (best-effort, resilient to empty/malformed input)
INPUT="$(cat || true)"

# Parse source field (graceful if jq unavailable or input malformed)
SOURCE=""
if command -v jq >/dev/null 2>&1; then
    SOURCE="$(printf '%s' "$INPUT" | jq -r '.source // ""' 2>/dev/null || true)"
fi

# Only act on compact events
if [[ "$SOURCE" != "compact" ]]; then
    exit 0
fi

# Build available skills list dynamically
SKILLS_LIST=""
COMMANDS_DIR="$HOME/.claude/commands"
if [[ -d "$COMMANDS_DIR" ]]; then
    SKILLS_LIST=$(ls -1 "$COMMANDS_DIR"/*.md 2>/dev/null | xargs -I{} basename {} .md | tr '\n' ', ' | sed 's/,$//')
fi

# Output critical reminders as additionalContext
# This gets injected into Claude's context after compaction
cat << EOF
{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": "## POST-COMPACTION CRITICAL RULES\n\n### 1. MCP-FIRST RULE (MANDATORY)\nALWAYS use MCP tools BEFORE CLI binaries:\n- GitHub: mcp__github__* (not gh CLI)\n- Search: mcp__grepai__* (not grep/rg)\n- Code Quality: mcp__codacy__* (not codacy-cli)\n- Browser: mcp__playwright__* (not npx playwright)\n- Docs: mcp__context7__* (for library docs)\n\n### 2. ENVIRONMENT AWARENESS\nALWAYS check environment variables and .env files:\n- Run: env | grep -E 'TOKEN|KEY|SECRET' (masked)\n- Check: /workspace/.env, .devcontainer/.env\n- MCP tokens are pre-configured in mcp.json\n- NEVER ask user for tokens if MCP is available\n\n### 3. NO AI MENTIONS IN COMMITS\nNEVER include in commit messages:\n- Co-Authored-By with Claude/Anthropic/AI/GPT\n- Generated by/with AI references\n- Robot emoji or AI tool names\nHook commit-validate.sh enforces this automatically.\n\n### 4. AVAILABLE SKILLS\nUse Skill tool to invoke: ${SKILLS_LIST:-git, review, search, plan, do, test, init, update}\n- /git --commit: Create branch + commit + PR\n- /review: AI-powered code review\n- /search: Documentation research\n- /plan: Planning mode\n- /do: Iterative task execution\n\n### 5. CONTEXT HIERARCHY\nRead CLAUDE.md files for full context:\n- /workspace/CLAUDE.md (project rules)\n- .devcontainer/CLAUDE.md (container config)\n- .devcontainer/images/CLAUDE.md (image details)\n- .devcontainer/features/*/CLAUDE.md (language rules)\nUpdate relevant CLAUDE.md when modifying code structure.\n\n### 6. GIT WORKFLOW\nNEVER commit directly to main/master.\nALWAYS use /git skill which creates branch + PR.\n\n### 7. SAFEGUARDS\nNEVER delete without explicit approval:\n- Files in .claude/ directory\n- Files in .devcontainer/ directory\n\n### 8. CONTEXT RECOVERY (POST-COMPACTION)\nAfter compaction, check for persisted state:\n- Plans: Glob .claude/plans/*.md (read most recent for current task)\n- Contexts: Glob .claude/contexts/*.md (research from /search)\n- Review fixes: .claude/plans/review-fixes-*.md (from /review)\nThese files survive compaction and contain valuable context.\nIf working on a task, read the relevant plan/context files to restore state.\n\n**Context was compacted. Verify current task state before continuing.**"
  }
}
EOF

exit 0
