/*
 * Documentation Theme — Color System
 *
 * Generated by /docs from accent color {{ACCENT_HEX}}
 *
 * Semantic palette:
 *   Primary  {{COLOR_PRIMARY_BORDER}}  (internal systems, persons)
 *   Data     {{COLOR_DATA_BORDER}}     (databases, stores)
 *   Async    {{COLOR_ASYNC_BORDER}}    (queues, messaging)
 *   External {{COLOR_EXTERNAL_BORDER}} (third-party, fixed gray)
 *   Error    {{COLOR_ERROR_BORDER}}    (failure paths, fixed red)
 *
 * Pattern: border = saturated, background = 10% alpha, text = constant
 */

/* ========================================================================
 * SECTION 1: MkDocs Material Custom Properties
 * ======================================================================== */

[data-md-color-scheme="slate"] {
  --md-primary-fg-color:              {{ACCENT_HEX}};
  --md-primary-fg-color--light:       {{COLOR_PRIMARY_BG}};
  --md-primary-fg-color--dark:        {{ACCENT_HEX}};
  --md-accent-fg-color:               {{ACCENT_HEX}};
  --md-accent-fg-color--transparent:  {{COLOR_PRIMARY_BG}};
}

/* ========================================================================
 * SECTION 2: C4 Diagram — Semantic Role Styling
 *
 * Defense layer 1 (CSS classes). Defense layer 2 is UpdateElementStyle
 * in each diagram's Mermaid block (see generation rules in docs.md).
 * C4 diagrams ignore Mermaid themes — CSS is the only global method.
 * Reference: https://github.com/mermaid-js/mermaid/issues/4906
 * ======================================================================== */

/* --- Primary: Person, System, Container, Component (internal) --- */
[data-md-color-scheme="slate"] .person .outer,
[data-md-color-scheme="slate"] .system .outer,
[data-md-color-scheme="slate"] .container .outer,
[data-md-color-scheme="slate"] .component .outer {
  fill: {{COLOR_PRIMARY_BG}} !important;
  stroke: {{COLOR_PRIMARY_BORDER}} !important;
}

/* --- External: Person_Ext, System_Ext --- */
[data-md-color-scheme="slate"] .personext .outer,
[data-md-color-scheme="slate"] .system_ext .outer,
[data-md-color-scheme="slate"] .systemext .outer {
  fill: {{COLOR_EXTERNAL_BG}} !important;
  stroke: {{COLOR_EXTERNAL_BORDER}} !important;
}

/* --- Data: ContainerDb, ComponentDb --- */
[data-md-color-scheme="slate"] .containerdb .outer,
[data-md-color-scheme="slate"] .componentdb .outer {
  fill: {{COLOR_DATA_BG}} !important;
  stroke: {{COLOR_DATA_BORDER}} !important;
}

/* --- Async: ContainerQueue, ComponentQueue --- */
[data-md-color-scheme="slate"] .containerqueue .outer,
[data-md-color-scheme="slate"] .componentqueue .outer {
  fill: {{COLOR_ASYNC_BG}} !important;
  stroke: {{COLOR_ASYNC_BORDER}} !important;
}

/* --- Deployment nodes (neutral dark) --- */
[data-md-color-scheme="slate"] .node .outer {
  fill: #2d2d2d !important;
  stroke: {{COLOR_EXTERNAL_BORDER}} !important;
}

/* --- All C4 text --- */
[data-md-color-scheme="slate"] .person text,
[data-md-color-scheme="slate"] .personext text,
[data-md-color-scheme="slate"] .system text,
[data-md-color-scheme="slate"] .systemext text,
[data-md-color-scheme="slate"] .system_ext text,
[data-md-color-scheme="slate"] .container text,
[data-md-color-scheme="slate"] .containerdb text,
[data-md-color-scheme="slate"] .containerqueue text,
[data-md-color-scheme="slate"] .component text,
[data-md-color-scheme="slate"] .componentdb text,
[data-md-color-scheme="slate"] .componentqueue text,
[data-md-color-scheme="slate"] .node text {
  fill: {{COLOR_TEXT}} !important;
}

/* --- Boundaries (dashed gray) --- */
[data-md-color-scheme="slate"] .boundary {
  stroke: {{COLOR_EXTERNAL_BORDER}} !important;
  stroke-dasharray: 5 5 !important;
}

[data-md-color-scheme="slate"] .boundary text {
  fill: #9ca3af !important;
}

/* --- Relationships (arrows + labels) --- */
[data-md-color-scheme="slate"] .messageLine0,
[data-md-color-scheme="slate"] .messageLine1 {
  stroke: {{COLOR_EDGE}} !important;
}

[data-md-color-scheme="slate"] .messageText {
  fill: {{COLOR_TEXT}} !important;
}

/* --- C4 background transparency --- */
[data-md-color-scheme="slate"] .mermaid svg {
  background-color: transparent !important;
}

/* ========================================================================
 * SECTION 3: Non-C4 Mermaid Overrides (Flowcharts, Sequence, State)
 *
 * CSS fallback for diagrams without explicit %%{init}%% blocks.
 * Diagrams with %%{init}%% will override these via inline styles.
 * ======================================================================== */

/* --- Flowchart nodes --- */
[data-md-color-scheme="slate"] .mermaid .node rect,
[data-md-color-scheme="slate"] .mermaid .node circle,
[data-md-color-scheme="slate"] .mermaid .node ellipse,
[data-md-color-scheme="slate"] .mermaid .node polygon,
[data-md-color-scheme="slate"] .mermaid .node path {
  fill: {{COLOR_PRIMARY_BG}} !important;
  stroke: {{COLOR_PRIMARY_BORDER}} !important;
}

[data-md-color-scheme="slate"] .mermaid .node .label {
  color: {{COLOR_TEXT}} !important;
}

/* --- Flowchart edges --- */
[data-md-color-scheme="slate"] .mermaid .edgePath .path {
  stroke: {{COLOR_EDGE}} !important;
}

[data-md-color-scheme="slate"] .mermaid .edgeLabel {
  background-color: {{COLOR_LABEL_BG}} !important;
  color: {{COLOR_TEXT}} !important;
}

/* --- Sequence diagram --- */
[data-md-color-scheme="slate"] .mermaid .actor {
  fill: {{COLOR_PRIMARY_BG}} !important;
  stroke: {{COLOR_PRIMARY_BORDER}} !important;
}

[data-md-color-scheme="slate"] .mermaid .actor-line {
  stroke: {{COLOR_EDGE}} !important;
}

[data-md-color-scheme="slate"] .mermaid text.actor {
  fill: {{COLOR_TEXT}} !important;
}

[data-md-color-scheme="slate"] .mermaid .activation0,
[data-md-color-scheme="slate"] .mermaid .activation1,
[data-md-color-scheme="slate"] .mermaid .activation2 {
  fill: {{COLOR_PRIMARY_BG}} !important;
  stroke: {{COLOR_PRIMARY_BORDER}} !important;
}

[data-md-color-scheme="slate"] .mermaid .note {
  fill: {{COLOR_LABEL_BG}} !important;
  stroke: {{COLOR_EXTERNAL_BORDER}} !important;
}

[data-md-color-scheme="slate"] .mermaid .note text {
  fill: {{COLOR_TEXT}} !important;
}

/* --- State diagram --- */
[data-md-color-scheme="slate"] .mermaid .stateGroup .composit {
  fill: {{COLOR_LABEL_BG}} !important;
}

[data-md-color-scheme="slate"] .mermaid .stateGroup rect {
  fill: {{COLOR_PRIMARY_BG}} !important;
  stroke: {{COLOR_PRIMARY_BORDER}} !important;
}

[data-md-color-scheme="slate"] .mermaid .stateGroup text {
  fill: {{COLOR_TEXT}} !important;
}
